getInShape copy/Practice Code/config/routes.rb
Letsplay::Application.routes.draw do
  resources :dummy_users

  get "welcome/index"

   root 'welcome#index'

end

getInShape copy/Practice Code/app/models/dummy_user.rb
class DummyUser < ActiveRecord::Base
end

getInShape copy/Practice Code/app/models/user_info.rb
class UserInfo < ActiveRecord::Base
belongs_to :user
validates :FirstName, :presence => true, :message => "Sorry you must enter a First Name"
validates :LastName, :presence => true, :message => "Sorry you must enter a Last Name"
validates :Username, :presence => true, :uniqueness => true, :message => "Sorry that username has been taken, please choose another."
validates :Password, :presence => true, :length => { :minimum => 8 }, :inclusion => { :in => [1,2,3,4,5,6,7,8,9] }, :message => "Password Invalid, please create a password with at least 8 characters, and with a least one numeric character."
validates :Sports, :presence => true
validates :Longitude, :presence => true, :numericality => true
validates :Latitude, :presence => true, :numericality => true
validates :TravelRadius, :presence => true, :numericality => true
validates :Descriptions, :presence => true
end

getInShape copy/Practice Code/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

getInShape copy/Practice Code/app/controllers/dummy_users_controller.rb
class DummyUsersController < ApplicationController
  before_action :set_dummy_user, only: [:show, :edit, :update, :destroy]

  # GET /dummy_users
  # GET /dummy_users.json
  def index
    @dummy_users = DummyUser.all
  end

  # GET /dummy_users/1
  # GET /dummy_users/1.json
  def show
  end

  # GET /dummy_users/new
  def new
    @dummy_user = DummyUser.new
  end

  # GET /dummy_users/1/edit
  def edit
  end

  # POST /dummy_users
  # POST /dummy_users.json
  def create
    @dummy_user = DummyUser.new(dummy_user_params)

    respond_to do |format|
      if @dummy_user.save
        format.html { redirect_to @dummy_user, notice: 'Dummy user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dummy_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @dummy_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dummy_users/1
  # PATCH/PUT /dummy_users/1.json
  def update
    respond_to do |format|
      if @dummy_user.update(dummy_user_params)
        format.html { redirect_to @dummy_user, notice: 'Dummy user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dummy_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dummy_users/1
  # DELETE /dummy_users/1.json
  def destroy
    @dummy_user.destroy
    respond_to do |format|
      format.html { redirect_to dummy_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dummy_user
      @dummy_user = DummyUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dummy_user_params
      params.require(:dummy_user).permit(:name, :email)
    end
end

getInShape copy/Practice Code/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

getInShape copy/Practice Code/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	  def create
    @user_info = user_data.new(user_info_params)

    respond_to do |format|
      if @user_info.save
        format.html { redirect_to @user_info, notice: 'User info was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_info }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end
  end
end

getInShape copy/Practice Code/app/helpers/application_helper.rb
module ApplicationHelper
end

getInShape copy/Practice Code/app/helpers/dummy_users_helper.rb
module DummyUsersHelper
end

getInShape copy/Practice Code/app/helpers/sessions_helper.rb
module SessionsHelper
end

getInShape copy/Practice Code/app/helpers/welcome_helper.rb
module WelcomeHelper
end

getInShape copy/Practice Code/app/views/dummy_users/_form.html.erb
<%= form_for(@dummy_user) do |f| %>
  <% if @dummy_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dummy_user.errors.count, "error") %> prohibited this dummy_user from being saved:</h2>

      <ul>
      <% @dummy_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

getInShape copy/Practice Code/app/views/dummy_users/edit.html.erb
<h1>Editing dummy_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @dummy_user %> |
<%= link_to 'Back', dummy_users_path %>

getInShape copy/Practice Code/app/views/dummy_users/index.html.erb
<h1>Listing dummy_users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dummy_users.each do |dummy_user| %>
      <tr>
        <td><%= dummy_user.name %></td>
        <td><%= dummy_user.email %></td>
        <td><%= link_to 'Show', dummy_user %></td>
        <td><%= link_to 'Edit', edit_dummy_user_path(dummy_user) %></td>
        <td><%= link_to 'Destroy', dummy_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dummy user', new_dummy_user_path %>

getInShape copy/Practice Code/app/views/dummy_users/new.html.erb
<h1>New dummy_user</h1>

<%= render 'form' %>

<%= link_to 'Back', dummy_users_path %>

getInShape copy/Practice Code/app/views/dummy_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dummy_user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dummy_user.email %>
</p>

<%= link_to 'Edit', edit_dummy_user_path(@dummy_user) %> |
<%= link_to 'Back', dummy_users_path %>

getInShape copy/Practice Code/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Letsplay</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

getInShape copy/Practice Code/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="mockup.css">
		<script type="text/javascript" src="jquery-1.10.2.js"></script>
		<script type="text/javascript" src ="mockup.js"></script>
	</head>
		<script>
			var x=document.getElementById("demo");
			function getLocation()
  			{
  			if (navigator.geolocation)
    		{
    			navigator.geolocation.getCurrentPosition(showPosition);
    		}
  			else{x.innerHTML="Geolocation is not supported by this browser.";}
  			}
			function showPosition(position)
  			{
  			x.innerHTML="Latitude: " + position.coords.latitude + 
  			"<br>Longitude: " + position.coords.longitude; 
  			}
		</script>
			<nav class="top">
			<ul>
				<li><a href="jsexcercises.html" id="logo">Let's Play!</a></li>
				<li><a href="jsexcercises.html" class="white">About</a></li>
				<li><a href="jsexcercises.html" class="white">Messages</a></li>
				<li><a href="jsexcercises.html" class="white">Help</a></li>
				<li><a href="jsexcercises.html" class="white">Feedback</a></li>
				<li><img src="IMG_0860.jpg"></li>
				<li id="melist"><a href="jsexcercises.html" id="me" class="white">Me</a></li>

			</ul>
		</nav>
	<body>

		<div id="wrapper">
			<h1> Getting Started!</h1>

			<div id="q0" class="question".>
				<h2> What is your name? </h2>
				<ul class="bullets">
					<p><input type="text" placeholder = "First Name"></input>
					<input type="text" placeholder = "Last Name"></input></p>
				</ul>
			</div>

			<div id="q1" class="question".>
				<h2> Choose a Username. </h2>
				<ul class="bullets">
					<p><input type="text" placeholder = "Username"></input></p>
				</ul>
			</div>

			<div id="q1" class="question".>
				<h2> Choose a Password. </h2>
				<p id="aside">Must be at least 8 characters.</p>
				<ul class="bullets">
					<p><input type="password" placeholder = "Password"></input></p>
				</ul>
			</div>

			<div id="q1" class="question">
				<h2> Which sports are you looking to play? </h2>
				<ul class="bullets">
					<p><input name="sport" type="checkbox">   Basketball</input></p>
					<p><input name="sport" type="checkbox">   Soccer</input></p>
					<p><input name="sport" type="checkbox">   Tennis</input></p>
				</ul>
			</div>

			<div id="q2" class="question">
				<h2> Describe your athletic experiences. </h2>
				<ul class="bullets">
					<form method="post" action="">
					<textarea name="comments" cols="25" rows="5">Enter your comments here...
					</textarea><br>
				</ul>
			</div>

<!-- 			<div id="q3" class="question">
				<h2>How big of a game do you want?</h2>
				<p>
				<form action="">
				<select name="team">
				<option value="empty"></option>
				<option value="one">1 on 1</option>
				<option value="two">2 on 2</option>
				<option value="three">3 on 3</option>
				<option value="five">5 on 5</option>
				</select>
				</form>
			</p>
			<ul class="bullets">
				<p><input name="group" type="radio">   1 on 1 </input></p>
				<p><input name="group" type="radio">   2 on 2 </input></p>
				<p><input name="group" type="radio">   3 on 3 </input></p>
				<p><input name="group" type="radio">   5 on 5 </input></p>
				
			</div> -->

			<div id="q4" class="question">
				<h2>Where are you?</h2>
				<ul class="bullets">
					<p><input name="loc" type="radio">   Use current location. (Recommended)</input><input type="submit" value="Find Me!" onclick="getLocation()"></input></p>
					<p><input name="loc" type="radio">   Enter zipcode   </input><input type="text" id="zipcode" placeholder="Enter zipcode"></p>
				</ul>
			</div>

			<div id="q5" class="question">
				<h2>How far are you willing to travel?</h2>
					<p id="aside">Selecting a wider radius gives you more options!</p>
					<ul class="bullets">
						<p><input name="travel" type="radio">   less than 5 miles</input></p>
						<p><input name="travel" type="radio">   5-10 miles</input></p>
						<p><input name="travel" type="radio">   10-15 miles</input></p>
						<p><input name="travel" type="radio">   more than 15 miles</input></p>
					</ul>
			</div>
			<div id="q6" class="question">
				<h2>When are you looking to play?</h2>
				<p id ="aside">Selecting a wider time frame gives you more choices!</p>
				<ul class="bullets">
					<p><input name="day" type="checkbox">   Sunday</input></p>
					<p><input name="day" type="checkbox">   Monday</input></p>
					<p><input name="day" type="checkbox">   Tuesday</input></p>
					<p><input name="day" type="checkbox">   Wednesday</input></p>
					<p><input name="day" type="checkbox">   Wednesday</input></p>
					<p><input name="day" type="checkbox">   Thursday</input></p>
					<p><input name="day" type="checkbox">   Friday</input></p>
					<p><input name="day" type="checkbox">   Saturday</input></p>
				</ul>
				 Between   <input type ="time"></input>   and   <input type ="time"></input>
			</ul>
			</div>
			<input type="submit" id="sendChat" value="Find a match!"></input>
		</div>
	</body>
</html>