getInShape copy/letsplay!/config/routes.rb
Letsplay::Application.routes.draw do
  resources :user_sports

  resources :users  #match '/local_location/:Location' => 'users#index', :as => 'local_location'
  

   root 'user_sports#index'

   get 'chat' => 'users#chat'
   

end

getInShape copy/letsplay!/app/models/sports_insatnce.rb
class SportsInsatnce < ActiveRecord::Base
	belongs_to :user
end

getInShape copy/letsplay!/app/models/user.rb
class User < ActiveRecord::Base
	# validates_presence_of :Sports
	# has_many :Sports

	#attr_accessible :Location, :Latitude, :Longitude
	geocoded_by :Location
	after_validation :geocode, :if => :Location_changed?



	def name
		return @user.FirstName @user.LastName
	end

end

getInShape copy/letsplay!/app/models/user_data.rb
class UserData < ActiveRecord::Base
end

getInShape copy/letsplay!/app/models/user_sport.rb
class UserSport < ActiveRecord::Base
end

getInShape copy/letsplay!/app/controllers/user_sports_controller.rb
class UserSportsController < ApplicationController
  before_action :set_user_sport, only: [:show, :edit, :update, :destroy]

  # GET /user_sports
  # GET /user_sports.json
  def index
    @user_sports = UserSport.all
  end

  # GET /user_sports/1
  # GET /user_sports/1.json
  def show
    # return yoursport
  end

  # GET /user_sports/new
  def new
    @user_sport = UserSport.new
  end

  # GET /user_sports/1/edit
  def edit
  end

  # POST /user_sports
  # POST /user_sports.json
  def create
    @user_sport = UserSport.new(user_sport_params)

    respond_to do |format|
      if @user_sport.save
        format.html { redirect_to @user_sport, notice: 'User sport was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_sport }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_sports/1
  # PATCH/PUT /user_sports/1.json
  def update
    respond_to do |format|
      if @user_sport.update(user_sport_params)
        format.html { redirect_to @user_sport, notice: 'User sport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sports/1
  # DELETE /user_sports/1.json
  def destroy
    @user_sport.destroy
    respond_to do |format|
      format.html { redirect_to user_sports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_sport
      @user_sport = UserSport.find(params[:id])
    end

    
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_sport_params
      params.require(:user_sport).permit(:sport, :user_id, :user_name)
    end
end

getInShape copy/letsplay!/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
  @users = User.all

  #   if params[:Location]
  #     @users = User.where(:Location => params[:Location])
  #   else
  #     @users = User.all
  #   end

  #   respond_to do |format|
  #     format.html 
  #     format.xml { render :xml => @users}
  # end
end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.all
    @user_sport = UserSport.all 
    # @sport = User.find(params[:Sports])
    
  end

  def chat
    @user = User.new
    @messager= @user.Username
  end


  # GET /users/new
  def new
    @user = User.new
    @person = User.all

  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:FirstName, :LastName, :Username, :Password, :Location, :Longitude, :Latitude, :SelfDescription)
    end
end

getInShape copy/letsplay!/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

getInShape copy/letsplay!/app/helpers/user_sports_helper.rb
module UserSportsHelper
end

getInShape copy/letsplay!/app/helpers/users_helper.rb
module UsersHelper
end

getInShape copy/letsplay!/app/views/user_sports/_form.html.erb
<%= form_for(@user_sport) do |f| %>
  <% if @user_sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_sport.errors.count, "error") %> prohibited this user_sport from being saved:</h2>

      <ul>
      <% @user_sport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sport %><br>
    <%= f.text_field :sport %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

getInShape copy/letsplay!/app/views/user_sports/edit.html.erb
<h1>Editing user_sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_sport %> |
<%= link_to 'Back', user_sports_path %>

getInShape copy/letsplay!/app/views/user_sports/index.html.erb
<h1>Listing user_sports</h1>

<table>
  <thead>
    <tr>
      <th>Sport</th>
      <th>User</th>
      <th>User name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_sports.each do |user_sport| %>
      <tr>
        <td><%= user_sport.sport %></td>
        <td><%= user_sport.user_id %></td>
        <td><%= user_sport.user_name %></td>
        <td><%= link_to 'Show', user_sport %></td>
        <td><%= link_to 'Edit', edit_user_sport_path(user_sport) %></td>
        <td><%= link_to 'Destroy', user_sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User sport', new_user_sport_path %>

getInShape copy/letsplay!/app/views/user_sports/new.html.erb
<h1>New user_sport</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sports_path %>

getInShape copy/letsplay!/app/views/user_sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sport:</strong>
  <%= @user_sport.sport %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_sport.user_id %>
</p>

<p>
  <strong>User name:</strong>
  <%= @user_sport.user_name %>
</p>


<p>
<strong>Other <%= @user_sport.sport %> Players: </strong>
<% @ballerlist= UserSport.where(:sport => @user_sport.sport).where.not(:user_id =>[@user_sport.user_id]) %>
<% @ballerlist.each do |i| %>

<% end %>

<table>
	<td><%=i.user_name %></td>
</table>

<%end%>

</p>

<%= link_to 'Edit', edit_user_sport_path(@user_sport) %> 
<%= link_to 'Back', user_sports_path %>

getInShape copy/letsplay!/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<script>
var x=document.getElementById("demo");
function getLocation()
  {
  if (navigator.geolocation)
    {
    navigator.geolocation.getCurrentPosition(showPosition,showError);
    }
  else{x.innerHTML="Geolocation is not supported by this browser.";}
  }

function showPosition(position)
  {
  var latlon=position.coords.latitude+","+position.coords.longitude;

  var img_url="http://maps.googleapis.com/maps/api/staticmap?center="
  +latlon+"&zoom=14&size=400x300&sensor=false";
  document.getElementById("mapholder").innerHTML="<img src='"+img_url+"'>";
  document.getElementById("lat").innerHTML=position.coords.latitude
  document.getElementById("long").innerHTML=position.coords.longitude

  }

function showError(error)
  {
  switch(error.code) 
    {
    case error.PERMISSION_DENIED:
      x.innerHTML="User denied the request for Geolocation."
      break;
    case error.POSITION_UNAVAILABLE:
      x.innerHTML="Location information is unavailable."
      break;
    case error.TIMEOUT:
      x.innerHTML="The request to get user location timed out."
      break;
    case error.UNKNOWN_ERROR:
      x.innerHTML="An unknown error occurred."
      break;
    }
  }
</script>


  <div class="field">
    <h2> What is your first name? </h2>
    <ul class="bullets">
      <p><%= f.text_field :FirstName, placeholder: "First Name"%><p>
    </ul>
  </div>

  <div class="field">
    <h2> What is your last name? </h2>
    <ul class="bullets">
      <%= f.text_field :LastName, placeholder: "Last Name" %>
    </ul>
  </div>

  <div class="field">
    <h2> Select a Username. </h2>
    <ul class="bullets">
      <%= f.text_field :Username, placeholder: "Username" %><br>
    </ul>
  </div>

  <div class="field">
    <h2> Choose a Password. </h2>
    <ul class="bullets">
      <%= f.password_field :Password, placeholder: "Password" %>
    </ul>
  </div>

<div class="field">
<!--   Latitude:<span id="lat"></span><br>
  Longitude:<span id="long"><span><br> -->
  lat:<span id="lat"></span><br>
  long:<span id="long"></span><br>
  <label for="user_latitude"></label>
 <!--  <input id="user_latitude" name="user[latitude]" type="button" onClick="getLocation()" value="Find Me!"/>  -->
<input type="button" onclick="getLocation()" value="Find Me!"></input>
<body>
  <div id="mapholder"></div>
</body>
</div>


  <div class="field">
    <h2> Latitude </h2>
    <ul class="bullets">
      <%=f.text_field :latitude %>
    </ul>
  </div>

<!--     <div class="field">
    <h2> Longitude </h2>
    <ul class="bullets">
      <%= f.text_field #:Longitude%>
    </ul>
  </div> -->

  <div class="field">
    <h2> Location </h2>
    <ul class="bullets">
      <%=f.text_field :Location %>
    </ul>
  </div>

  <div class="field">
    <h2> Describe you athletic Skillsssss </h2>
    <ul class="bullets">
      <%= f.text_area :SelfDescription, placeholder: "Enter Description Here" %>
    </ul>
  </div>

  <div class="actions">
    <%= f.submit %>
  
<% end %>
</div>

getInShape copy/letsplay!/app/views/users/chat.html.erb
<html>
<head>
  <script src="https://cdn.firebase.com/v0/firebase.js"></script>
  <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js'></script>
  <link rel="stylesheet" type="text/css" href="https://www.firebase.com/css/example.css">
</head>
<body>
<div id='messagesDiv'></div>
<input type='text' id='nameInput' value="<%= @user.Username %>">
<input type='text' id='messageInput' placeholder='Message...'>
<script>

  // Get a reference to the root of the chat data.
  var messagesRef = new Firebase('https://hhypmgtp3us.firebaseio-demo.com/');

  // When the user presses enter on the message input, write the message to firebase.
  $('#messageInput').keypress(function (e) {
    if (e.keyCode == 13) {
      var name = $('#nameInput').val();
      var text = $('#messageInput').val();
      messagesRef.push({name:name, text:text});
      $('#messageInput').val('');
    }
  });

  // Add a callback that is triggered for each chat message.
  messagesRef.limit(10).on('child_added', function (snapshot) {
    var message = snapshot.val();
    $('<div/>').text(message.text).prepend($('<em/>')
      .text(message.name+': ')).appendTo($('#messagesDiv'));
    $('#messagesDiv')[0].scrollTop = $('#messagesDiv')[0].scrollHeight;
  });
</script>
</body>
</html>

getInShape copy/letsplay!/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

getInShape copy/letsplay!/app/views/users/index.html.erb
<h1>This is where we can find people who want to play.</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Username</th>
      <th>Password</th>
      <th>Location</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Self Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.FirstName %></td>
        <td><%= user.LastName %></td>
        <td><%= user.Username %></td>
        <td><%= user.Password %></td>
        <td><%= user.Location %></td>
        <td><%= user.Longitude %></td>
        <td><%= user.Latitude %></td>
        <td><%= user.SelfDescription %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

getInShape copy/letsplay!/app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<nav class="top">
	<ul>
		<li><a href="jsexcercises.html" id="logo">Let's Play!</a></li>
		<li><a href="jsexcercises.html" class="white">About</a></li>
		<li><a href="jsexcercises.html" class="white">Messages</a></li>
		<li><a href="jsexcercises.html" class="white">Help</a></li>
		<li><a href="jsexcercises.html" class="white">Feedback</a></li>
		<li><img src="IMG_0860.jpg"></li>
		<li id="melist"><a href="jsexcercises.html" id="me" class="white">Me</a></li>
	</ul>
</nav>

<body>
	<div id="wrapper">
		<h1>Getting Started!</h1>
		<%= render 'form' %>
	</div>
</body>
</html>
<%= link_to 'Back', users_path %>

getInShape copy/letsplay!/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<html>
<body>
<ul>


<p>
  <strong>Name:</strong>
  <%= @user.FirstName %> <%= @user.LastName %>
</p>

<!-- <p>
  <strong>Lastname:</strong>
  
</p> -->

<p>
  <strong>Username:</strong>
  <%= @user.Username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.Password %>
</p>



<p>
  <strong>Location:</strong>
  <%= @user.Location %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @user.Longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @user.Latitude %>
</p>

<p>
  <strong>Self Description:</strong>
  <%= @user.SelfDescription %>
</p>



<% @user_pref= UserSport.where(:user_id=> [@user.id]) %>
<% @user_pref.each do |game| %>
    <% @mySport = game.sport %><br>
    <% @sport_users= UserSport.where(:sport=> [game.sport]).where.not(:user_id=>[@user.id])%>
    <thead><strong>People in <%= @user.Location %> who play <%=@mySport%>!</strong><br></thead>
    <% @sport_users.each do |baller| %>
        <% @baller_id = baller.user_id%>
        <% @player = User.find(@baller_id)%><br>
        <% @loclist = User.where(:Location=>[@user.Location],:id =>[@baller_id]) %>  

          <% @loclist.each do |i| %>
            <p>
              
              <table>
                <td><%= i.FirstName %> <%= i.LastName %></td>
                <td>Send <%= i.FirstName %> <%= i.LastName %> a <%=link_to 'a message!', chat_path %> </td>
                
                
            </table>
            </p> 
          <%end%>
      <% end %>
<% end %>
</ul>
</body>
</html>

<%= link_to 'Edit', edit_user_path(@user) %> 
<%= link_to 'Back', users_path %>

getInShape copy/letsplay!/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="mockup.css">
<script type="text/javascript" src="jquery-1.10.2.js"></script>
<script type="text/javascript" src ="mockup.js"></script>
</head>
<script>
var x=document.getElementById("demo");
function getLocation()
   {
   if (navigator.geolocation)
     {
     navigator.geolocation.getCurrentPosition(showPosition);
     }
   else{x.innerHTML="Geolocation is not supported by this browser.";}
   }
function showPosition(position)
   {
   x.innerHTML="Latitude: " + position.coords.latitude +
   "<br>Longitude: " + position.coords.longitude;
   }
</script>
<nav class="top">
<ul>
<li><a href="jsexcercises.html" id="logo">Let's Play!</a></li>
<li><a href="jsexcercises.html" class="white">About</a></li>
<li><a href="jsexcercises.html" class="white">Messages</a></li>
<li><a href="jsexcercises.html" class="white">Help</a></li>
<li><a href="jsexcercises.html" class="white">Feedback</a></li>
<li><img src="IMG_0860.jpg"></li>
<li id="melist"><a href="jsexcercises.html" id="me" class="white">Me</a></li>

</ul>
</nav>
<body>

<div id="wrapper">
<h1> Getting Started</h1>
<div id="q1" class="question">
<h2> Which sport are you looking to play? </h2>
<ul class="bullets">
<p><input name="sport" type="radio"> Basketball</input></p>
<p><input name="sport" type="radio"> Soccer</input></p>
<p><input name="sport" type="radio"> Tennis</input></p>
</ul>
</div>

<div id="q2" class="question">
<h2> At what skill level would you like to play at? </h2>
<ul class="bullets">
<p><input name="skill" type="radio"> Beginner </input></p>
<p><input name="skill" type="radio"> Intermediate </input></p>
<p><input name="skill" type="radio"> Advanced</input></p>
</ul>
</div>

<div id="q3" class="question">
<h2>How big of a game do you want?</h2>
<!-- <p>
<form action="">
<select name="team">
<option value="empty"></option>
<option value="one">1 on 1</option>
<option value="two">2 on 2</option>
<option value="three">3 on 3</option>
<option value="five">5 on 5</option>
</select>
</form>
</p> -->
<ul class="bullets">
<p><input name="group" type="radio"> 1 on 1 </input></p>
<p><input name="group" type="radio"> 2 on 2 </input></p>
<p><input name="group" type="radio"> 3 on 3 </input></p>
<p><input name="group" type="radio"> 5 on 5 </input></p>

</div>

<div id="q4" class="question">
<h2>Where are you?</h2>
<ul class="bullets">
<p><input name="loc" type="radio"> Use current location. (Recommended)</input><input type="submit" value="Find Me!" onclick="getLocation()"></input></p>
<p><input name="loc" type="radio"> Enter zipcode </input><input type="text" id="zipcode" placeholder="Enter zipcode"></p>
</ul>
</div>

<div id="q5" class="question">
<h2>How far are you willing to travel?</h2>
<p id="aside">Selecting a wider radius gives you more options!</p>
<ul class="bullets">
<p><input name="travel" type="radio"> less than 5 miles</input></p>
<p><input name="travel" type="radio"> 5-10 miles</input></p>
<p><input name="travel" type="radio"> 10-15 miles</input></p>
<p><input name="travel" type="radio"> more than 15 miles</input></p>
</ul>
</div>
<div id="q6" class="question">
<h2>When are you looking to play?</h2>
<p id ="aside">Selecting a wider time frame gives you more choices!</p>
<ul class="bullets">
<input type="date"></input> between <input type ="time"></input> and <input type ="time"></input>
</ul>
</div>
<input type="submit" id="sendChat" value="Find a match!"></input>
</div>
</body>
</html>